/**
 * TypeScript interfaces for landing page generation.
 * Ported from Python models in the loop-agent-sdk.
 */

// Color palette interface
export interface ColorPalette {
  primary: string; // #hex
  secondary: string; // #hex
  accent: string; // #hex for CTAs
  neutral: string[]; // 10 grayscale shades from near-white to near-black
  semantic: {
    success: string;
    warning: string;
    error: string;
    info: string;
  };
}

// Typography interface
export interface Typography {
  headingFont: string;
  bodyFont: string;
  headingWeights: number[];
  bodyWeights: number[];
  scale: Record<string, string>; // xs, sm, base, lg, xl, 2xl...6xl
}

// Spacing interface
export interface Spacing {
  scale: string[]; // ["0.25rem", "0.5rem", ..., "8rem"]
  contentMaxWidth: string; // "1280px"
  sectionPadding: {
    mobile: string;
    tablet: string;
    desktop: string;
  };
}

// Imagery style interface
export interface ImageryStyle {
  mood: string; // "modern and professional"
  colorTreatment: "vibrant" | "muted" | "monochrome";
  composition: "clean" | "busy" | "minimal" | "dynamic";
  photographyVsIllustration: "photography" | "illustration" | "mixed";
}

// Business info interface
export interface BusinessInfo {
  name: string;
  tagline?: string;
  email?: string;
  phone?: string;
  location?: string;
  currency?: string;
  services?: string[];
}

// Complete Brand Kit interface
export interface BrandKit {
  name: string;
  colors: ColorPalette;
  typography: Typography;
  spacing: Spacing;
  imageryStyle: ImageryStyle;
  personalityTraits: string[]; // 2-5 adjectives
  logoUrl?: string;
  businessInfo?: BusinessInfo;
}

// Compressed design tokens for prompts
export interface DesignTokens {
  colorPalette: {
    primary: string;
    secondary: string;
    accent: string;
    [key: string]: string; // neutral_0, neutral_1, etc.
  };
  typography: {
    headingFont: string;
    bodyFont: string;
    headingWeights: number[];
    bodyWeights: number[];
    scale: Record<string, string>;
  };
  spacing: {
    scale: string[];
    contentMaxWidth: string;
    sectionPadding: {
      mobile: string;
      tablet: string;
      desktop: string;
    };
  };
  imageryStyle: ImageryStyle;
  brandPersonality: string[];
}

// Content structure for a section
export interface SectionContent {
  type: string;
  compositionPattern: string;
  content: {
    headline?: string;
    subheadline?: string;
    sectionHeading?: string;
    sectionSubheading?: string;
    ctaPrimaryText?: string;
    ctaPrimaryHref?: string;
    ctaSecondaryText?: string;
    ctaSecondaryHref?: string;
    items?: Array<{
      heading: string;
      body: string;
      iconNeeded?: boolean;
      iconContext?: string;
    }>;
    [key: string]: unknown;
  };
  imageNeeded?: boolean;
  imageContext?: string;
}

// Complete content structure
export interface ContentStructure {
  sections: SectionContent[];
}

// Utility classes generated by design system
export interface UtilityClasses {
  heading_1: string;
  heading_2: string;
  heading_3: string;
  body_large: string;
  body_text: string;
  cta_primary: string;
  cta_secondary: string;
  card: string;
  container: string;
  section: string;
  link: string;
  [key: string]: string;
}

// Image needed for generation
export interface ImageNeeded {
  id: string;
  alt: string;
  context: string;
}

// HTML generation result
export interface HTMLGenerationResult {
  html: string;
  sections: Record<string, string>;
  imagesNeeded: ImageNeeded[];
}

// Complete generation result
export interface GenerationResult {
  html: string;
  sections: string[];
  tokensUsed: number;
  cost: number;
}

// Brand kit generation result
export interface BrandKitResult {
  brandKit: BrandKit;
  confidence: number;
  warnings: string[];
}

// Industry template color palette option
export interface ColorPaletteOption {
  name: string;
  primary: string;
  secondary: string;
  accent: string;
  neutralBase: "warm" | "cool";
}

// Industry template typography option
export interface TypographyOption {
  heading: string;
  body: string;
}

// Industry template
export interface IndustryTemplate {
  colorPalettes: ColorPaletteOption[];
  typographyOptions: TypographyOption[];
  imageryDefaults: {
    mood: string;
    colorTreatment: "vibrant" | "muted" | "monochrome";
    composition: "clean" | "busy" | "minimal" | "dynamic";
    photographyVsIllustration: "photography" | "illustration" | "mixed";
  };
  personalityPool: string[];
}

// Generation state enum
export type GenerationState =
  | "init"
  | "analyzing_brand"
  | "generating_design_system"
  | "planning_content"
  | "generating_html"
  | "complete"
  | "error";
